# data-denoise-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-denoise-app
spec:
  selector:
    matchLabels:
      app: data-denoise-app
  replicas: 1 # You can increase this for more pods
  template:
    metadata:
      labels:
        app: data-denoise-app
    spec:
      containers:
      - name: data-denoise-container
        image: juliusperez/data-denoise:latest
        ports:
        - containerPort: 80 # The port your Python app listens on
        #command: ["/bin/bash", "-c", "tail -f /dev/null"] # Keeps the container running
        stdin: true # Keep STDIN open
        tty: true   # Allocate a TT
